version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.1
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.26
    - 14.14.30
    - 14.14.31
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.9.0
  - dependency-name: ts-loader
    versions:
    - 8.0.16
    - 8.0.18
    - 8.1.0
    - 9.0.0
    - 9.1.0
  - dependency-name: ajv
    versions:
    - 7.0.3
    - 7.1.1
    - 7.2.1
    - 8.0.5
    - 8.1.0
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.17
    - 7.13.1
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: i18next
    versions:
    - 19.8.9
    - 19.9.0
    - 19.9.1
    - 20.0.0
    - 20.1.0
    - 20.2.1
  - dependency-name: jsdom
    versions:
    - 16.5.0
    - 16.5.2
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: ts-jest
    versions:
    - 26.5.4
  - dependency-name: "@typescript-eslint/typescript-estree"
    versions:
    - 4.15.0
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.19.0
    - 4.20.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.7.0
    - 7.8.0
  - dependency-name: electron-json-storage
    versions:
    - 4.4.0
  - dependency-name: electron
    versions:
    - 11.3.0
    - 12.0.1
  - dependency-name: css-loader
    versions:
    - 5.0.2
    - 5.1.1
    - 5.1.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.0.0
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.18
    - 7.13.2
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.17
    - 7.13.0
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.10
    - 7.12.17
    - 7.13.2
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.6
    - 1.3.8
  - dependency-name: emojilib
    versions:
    - 3.0.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
  - dependency-name: electron-context-menu
    versions:
    - 2.4.0
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.13.0
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
