name: reviewdog

on:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review

  stylelint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          reporter: github-pr-review
          stylelint_input: '**/*.vue'
